language: php

php:
  - 5.6
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0

before_script:
  - travis_retry composer self-update -vvv
  - travis_retry composer install --no-interaction --prefer-source -vvv

script:
  - ls -l